node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
          sh 'npm install --only=dev'
          sh 'npm test'
          sh 'pwd'
       }
     }
   }
   stage('docker build/push') {
     sh 'pwd'
     dir("basics"){
          docker.withRegistry('https://index.docker.io/v1/', 'slava-dockerhub') {
            def app = docker.build("slavapas13/nodejs-demo:${commit_id}", '.').push()
          }
          sh 'pwd'
     }
   }
   stage('docker run') {
     sh label: '', script: """docker rm docker_test || true
      docker run --rm -tid --name docker_test -p 3000 slavapas13/nodejs-demo:${commit_id}
      docker kill docker_test
      
      """
     }
   }

© 2022 GitHub, Inc.
