node {
   def commit_id
   stage('step a') {
      sh 'pwd'
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'pwd'
       dir("basics"){
          sh 'pwd'
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
      sh 'pwd'
     docker.withRegistry('https://index.docker.io/v1/', 'slava-dockerhub') {
       def app = docker.build("slavapas13/nodejs-demo:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''docker rm docker_test || true
     sh 'pwd'
      dir("basics"){
         sh 'pwd'
         docker run --rm -tid --name docker_test -p 3000 slavapas13/nodejs-demo:${commit_id}
         docker kill docker_test
       }      
      '''
     }
   }

